catalog:
  '@types/node': ^12.20.55
  'tslib': ^2.8.1
packages:
  - commons
  - headers
  - uri-image-parser
  - uri-jdbc-protocol
  - uri-mysql-protocol
  - uri-postgres-protocol
  - uri-sqlite-protocol
  - uri-tds-protocol
  - uri-x4e-parser
  - uri
  - web-service
  - x4e
